[title]
# C:\Windows\Fonts
font_family = "Microsoft YaHei"
font_size = 14
color = [ 255, 255, 255, 255]
bg_color = [ 0, 0, 0, 0,]
border_color = [ 0, 0, 0, 0,]
border_width = 0
min_width = 12
max_width = 20
padding = 1

[content]
font_family = "Microsoft YaHei"
font_size = 12
color = [ 255, 255, 255, 255,]
bg_color = [ 0, 0, 0, 0,]
border_color = [ 0, 0, 0, 0,]
border_width = 0
line_spacing = 3
max_lines = 2
width = 320
ellipsis = "[...]"

[widget]
padding = [ 3, 3, 3, 3,]
spacing = 5
width = 350
initial_x = 100
initial_y = 100
border_radius = 8
border_width = 4

[pinned]
bg_colors = [ [ 155, 68, 0, 255,], [ 179, 92, 68, 255,],]
border_colors = [ [ 84, 67, 50, 255,], [ 137, 103, 71, 255,],]

[unpinned]
bg_colors = [ [ 44, 79, 84, 255,], [ 31, 49, 52, 255,],]
border_colors = [ [ 137, 103, 71, 255,], [ 84, 67, 50, 255,],]

[button]
size = [ 24, 20,]
normal_color = [ 255, 204, 51, 255,]
hover_color = [ 255, 255, 153, 255,]
pinned_color = [ 200, 50, 50, 255,]
pinned_hover_color = [ 166, 0, 0, 255,]
review_color = [ 200, 50, 50, 255,]
review_hover_color = [ 166, 0, 0, 255,]
border_radius = 10
show_pin = true
show_copy = true
show_paste = true
show_type = true
show_review = true

[global]
max_total_groups = 12
auto_close_timeout = 1000
window_stay_on_top = true
window_frameless = true
