[project]
name = "CapsWriter-Offline"
authors = [{ name = "HaujetZhao" }]
maintainers = [{ name = "H1DDENADM1N" }, { name = "JoanthanWu" }]
version = "3.5.0"
description = "离线语音输入简/繁体、中译英、字幕转录；在线多译多、云剪贴板等等 （选用SenseVoice模型 支持中粤英日韩多语种）"
readme = "readme.md"
requires-python = "==3.13.11"
dependencies = [
    "loguru>=0.7.3",
    "numpy>=2.4.0",
    "pyside6>=6.10.1",
    "rich>=14.2.0",
    "tomlkit>=0.13.3",
]

[dependency-groups]
server = [
    "flask>=3.1.2",
    "httpx>=0.28.1",
    "jieba>=0.42.1",
    "qt-material>=2.17",
    "sacremoses>=0.1.1",
    "sentencepiece>=0.2.1",
    "sherpa-onnx>=1.12.20",
    "torch>=2.9.1",
    "transformers>=4.57.3",
    "websockets>=15.0.1",
]
client = [
    "clipman>=3.3.3",
    "flask>=3.1.2",
    "httpx>=0.28.1",
    "keyboard>=0.13.5",
    "libretranslatepy>=2.1.4",
    "opencc-python-reimplemented>=0.1.7",
    "psutil>=7.2.1",
    "pycaw>=20251023",
    "pypinyin>=0.55.0",
    "pywin32>=311",
    "qt-material>=2.17",
    "qrcode>=8.2",
    "sounddevice>=0.5.3",
    "srt>=3.5.3",
    "typer>=0.21.0",
    "watchdog>=6.0.0",
    "websockets>=15.0.1",
    "zai-sdk>=0.2.0",
]
editconfiggui = [
    "keyboard>=0.13.5",
    # siui  PySide6-SiliconUI  https://github.com/H1DDENADM1N/PySide6-SiliconUI
    # Note: siui is not available on PyPI, need to download and copy to .venv/Lib/site-packages and ./site-packages manually
]

[project.optional-dependencies]
dev = []

[project.urls]
Repository = "https://github.com/H1DDENADM1N/CapsWriter-Offline"
Issues = "https://github.com/H1DDENADM1N/CapsWriter-Offline/issues"
